### ISSUE TITLE
Encoding of `EUKREF-CILIOPHORA.tsv` file

### ISSUE THREAD

**Issue by kbseah** [eukref/curation#1]
What is the encoding of the file `EUKREF-CILIOPHORA.tsv`? There are some special characters that do not show up properly in `less` and text editors. 

The `file` command doesn't seem to be able to guess it, reporting only "Non-ISO extended-ASCII text, with very long lines, with CR line terminators". 

Thanks in advance for your help!

**Comment by vaulot** [comment]
Hi Brandon

I have incorporated parts of this file into the PR2 database (https://github.com/pr2database/pr2database).

In the process I had to clean up the  `EUKREF-CILIOPHORA.tsv` file.  I am attaching the cleaned up file.  Hope it helps.  Daniel


[EUKREF-CILIOPHORA_corrected_v2.0.tsv.gz](https://github.com/eukref/curation/files/3455183/EUKREF-CILIOPHORA_corrected_v2.0.tsv.gz)

**Comment by kbseah** [comment]
Thank you @vaulot ! There are a few more formatting/special characters issues (e.g. line breaks within a cell) in the file that are not a problem when opening with Excel or a spreadsheet program, but become a problem when trying to process it with command-line tools. Do you mind if use your version as the basis for further cleanups and a subsequent pull request?

**Comment by vaulot** [comment]
No of course, you are very welcome to use this version... Cheers.  Daniel

**Comment by kbseah** [comment]
Encoding of the file appears to be Mac OS Roman, encoding `MACINTOSH` when using `iconv`.
